const $=s=>document.querySelector(s),code=$('#code'),lines=$('#lines'),out=$('#output'),run=$('#run'),status=$('#status'),meta=$('#meta'),card=$('.card');let controller,saveTimer;
function nums(){lines.textContent=code.value.split('\n').map((_,i)=>i+1).join('\n')}
function state(text,kind=''){status.className=kind;status.querySelector('span').textContent=text}
function save(){localStorage.setItem('nc-c-code',code.value);localStorage.setItem('nc-c-stdin',$('#stdin').value);localStorage.setItem('nc-c-flags',$('#flags').value);meta.textContent='Avtomatik yadda saxlanıldı';meta.classList.add('saved');setTimeout(()=>meta.classList.remove('saved'),900)}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(save,450)}
async function health(){try{const r=await fetch('https://wandbox.org/api/list.json');if(!r.ok)throw 0;state('Compiler hazırdır','ok');run.disabled=false}catch{state('Compiler əlçatan deyil','bad');out.className='err';out.textContent='Compiler xidmətinə qoşulmaq mümkün olmadı. Hosting CORS və CSP qaydalarını yoxlayın.'}}
function formatResult(d){const parts=[];if(d.compiler_error)parts.push('⛔ COMPILER ERROR\n'+d.compiler_error);if(d.compiler_message)parts.push('ℹ COMPILER MESSAGE\n'+d.compiler_message);if(d.program_output)parts.push('✓ PROGRAM OUTPUT\n'+d.program_output);if(d.program_error)parts.push('⛔ PROGRAM ERROR\n'+d.program_error);if(d.program_message)parts.push('ℹ PROGRAM MESSAGE\n'+d.program_message);return parts.join('\n\n')||'✓ Proqram çıxış vermədən uğurla tamamlandı.'}
async function execute(){if(controller){controller.abort();controller=null;run.textContent='▶ Compile & Run';out.className='err';out.textContent='İcra dayandırıldı.';return}controller=new AbortController();run.textContent='■ Dayandır';out.className='';out.textContent='Kompilyasiya və icra aparılır...';meta.textContent='İşləyir';const started=performance.now();try{const r=await fetch('https://wandbox.org/api/compile.json',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({code:code.value,compiler:$('#compiler').value,stdin:$('#stdin').value,'compiler-option-raw':$('#flags').value,save:false})});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();out.textContent=formatResult(d);out.className=(d.compiler_error||d.program_error||Number(d.status)!==0)?'err':'ok';meta.textContent=`${Math.round(performance.now()-started)} ms • exit ${d.status??0}`}catch(e){if(e.name!=='AbortError'){out.className='err';out.textContent='Xidmət xətası: '+e.message;meta.textContent='Xəta'}}finally{controller=null;run.textContent='▶ Compile & Run'}}
function download(){const b=new Blob([code.value],{type:'text/x-c'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='main.c';a.click();URL.revokeObjectURL(a.href)}
code.oninput=()=>{nums();scheduleSave()};code.onscroll=()=>lines.scrollTop=code.scrollTop;code.onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();code.setRangeText('    ',code.selectionStart,code.selectionEnd,'end');nums()}if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();execute()}};
run.onclick=execute;$('#download').onclick=download;$('#copyOutput').onclick=async()=>{await navigator.clipboard.writeText(out.textContent);meta.textContent='Çıxış kopyalandı'};$('#fullscreen').onclick=()=>{card.classList.toggle('full');$('#fullscreen').textContent=card.classList.contains('full')?'Kiçilt':'Tam ekran'};
$('#profile').onchange=e=>{if(e.target.value){$('#flags').value=e.target.value;scheduleSave()}else $('#flags').focus()};$('#flags').oninput=()=>{$('#profile').value='';scheduleSave()};$('#stdin').oninput=scheduleSave;
$('#clear').onclick=()=>{code.value='';$('#stdin').value='';nums();save();out.className='';out.textContent='Redaktor təmizləndi.'};$('#sample').onclick=()=>{code.value='#include <stdio.h>\n\nint main(void) {\n    int n;\n    printf("Bir ədəd daxil edin: ");\n    if (scanf("%d", &n) != 1) return 1;\n    printf("Kvadratı: %d\\n", n * n);\n    return 0;\n}';$('#stdin').value='12';nums();save()};
const saved=localStorage.getItem('nc-c-code');if(saved!==null)code.value=saved;$('#stdin').value=localStorage.getItem('nc-c-stdin')||'';$('#flags').value=localStorage.getItem('nc-c-flags')||$('#flags').value;nums();health();
