/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as CRouteImport } from './routes/c'
import { Route as HtmlRouteImport } from './routes/html'
import { Route as JavascriptRouteImport } from './routes/javascript'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PythonRouteImport } from './routes/python'
import { Route as SqlRouteImport } from './routes/sql'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const CRoute = CRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlRoute = HtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptRoute = JavascriptRouteImport.update({
  id: '/javascript',
  path: '/javascript',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRoute
  '/c': typeof CRoute
  '/html': typeof HtmlRoute
  '/javascript': typeof JavascriptRoute
  '/more': typeof MoreRoute
  '/preview': typeof PreviewRoute
  '/python': typeof PythonRoute
  '/sql': typeof SqlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangRoute
  '/c': typeof CRoute
  '/html': typeof HtmlRoute
  '/javascript': typeof JavascriptRoute
  '/more': typeof MoreRoute
  '/preview': typeof PreviewRoute
  '/python': typeof PythonRoute
  '/sql': typeof SqlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRoute
  '/c': typeof CRoute
  '/html': typeof HtmlRoute
  '/javascript': typeof JavascriptRoute
  '/more': typeof MoreRoute
  '/preview': typeof PreviewRoute
  '/python': typeof PythonRoute
  '/sql': typeof SqlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/c'
    | '/html'
    | '/javascript'
    | '/more'
    | '/preview'
    | '/python'
    | '/sql'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/c'
    | '/html'
    | '/javascript'
    | '/more'
    | '/preview'
    | '/python'
    | '/sql'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/c'
    | '/html'
    | '/javascript'
    | '/more'
    | '/preview'
    | '/python'
    | '/sql'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRoute
  CRoute: typeof CRoute
  HtmlRoute: typeof HtmlRoute
  JavascriptRoute: typeof JavascriptRoute
  MoreRoute: typeof MoreRoute
  PreviewRoute: typeof PreviewRoute
  PythonRoute: typeof PythonRoute
  SqlRoute: typeof SqlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c': {
      id: '/c'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html': {
      id: '/html'
      path: '/html'
      fullPath: '/html'
      preLoaderRoute: typeof HtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript': {
      id: '/javascript'
      path: '/javascript'
      fullPath: '/javascript'
      preLoaderRoute: typeof JavascriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRoute,
  CRoute: CRoute,
  HtmlRoute: HtmlRoute,
  JavascriptRoute: JavascriptRoute,
  MoreRoute: MoreRoute,
  PreviewRoute: PreviewRoute,
  PythonRoute: PythonRoute,
  SqlRoute: SqlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
