/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CRouteImport } from './routes/c'
import { Route as HtmlRouteImport } from './routes/html'
import { Route as JavascriptRouteImport } from './routes/javascript'
import { Route as PythonRouteImport } from './routes/python'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as HtmlPreviewRouteImport } from './routes/html.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CRoute = CRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlRoute = HtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptRoute = JavascriptRouteImport.update({
  id: '/javascript',
  path: '/javascript',
  getParentRoute: () => rootRouteImport,
} as any)
const PythonRoute = PythonRouteImport.update({
  id: '/python',
  path: '/python',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlPreviewRoute = HtmlPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => HtmlRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c': typeof CRoute
  '/html': typeof HtmlRouteWithChildren
  '/javascript': typeof JavascriptRoute
  '/python': typeof PythonRoute
  '/sql': typeof SqlRoute
  '/html/preview': typeof HtmlPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c': typeof CRoute
  '/html': typeof HtmlRouteWithChildren
  '/javascript': typeof JavascriptRoute
  '/python': typeof PythonRoute
  '/sql': typeof SqlRoute
  '/html/preview': typeof HtmlPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c': typeof CRoute
  '/html': typeof HtmlRouteWithChildren
  '/javascript': typeof JavascriptRoute
  '/python': typeof PythonRoute
  '/sql': typeof SqlRoute
  '/html/preview': typeof HtmlPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/c' | '/html' | '/javascript' | '/python' | '/sql' | '/html/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/c' | '/html' | '/javascript' | '/python' | '/sql' | '/html/preview'
  id:
    | '__root__'
    | '/'
    | '/c'
    | '/html'
    | '/javascript'
    | '/python'
    | '/sql'
    | '/html/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CRoute: typeof CRoute
  HtmlRoute: typeof HtmlRouteWithChildren
  JavascriptRoute: typeof JavascriptRoute
  PythonRoute: typeof PythonRoute
  SqlRoute: typeof SqlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c': {
      id: '/c'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html': {
      id: '/html'
      path: '/html'
      fullPath: '/html'
      preLoaderRoute: typeof HtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript': {
      id: '/javascript'
      path: '/javascript'
      fullPath: '/javascript'
      preLoaderRoute: typeof JavascriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/python': {
      id: '/python'
      path: '/python'
      fullPath: '/python'
      preLoaderRoute: typeof PythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html/preview': {
      id: '/html/preview'
      path: '/preview'
      fullPath: '/html/preview'
      preLoaderRoute: typeof HtmlPreviewRouteImport
      parentRoute: typeof HtmlRoute
    }
  }
}

interface HtmlRouteChildren {
  HtmlPreviewRoute: typeof HtmlPreviewRoute
}

const HtmlRouteChildren: HtmlRouteChildren = {
  HtmlPreviewRoute: HtmlPreviewRoute,
}

const HtmlRouteWithChildren = HtmlRoute._addFileChildren(HtmlRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CRoute: CRoute,
  HtmlRoute: HtmlRouteWithChildren,
  JavascriptRoute: JavascriptRoute,
  PythonRoute: PythonRoute,
  SqlRoute: SqlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
